In [42]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [43]:
import pickle
new_data = pickle.load(open('dataset21.pkl','rb'))
new_data

Age  Income  LoanAmount  CreditScore  MonthsEmployed  InterestRate  \
0        56   85994       50587          520              80         15.23   
1        69   50432      124440          458              15          4.81   
2        46   84208      129188          451              26         21.17   
3        32   31713       44799          743               0          7.07   
4        60   20437        9139          633               8          6.51   
...     ...     ...         ...          ...             ...           ...   
255342   19   37979      210682          541             109         14.11   
255343   32   51953      189899          511              14         11.55   
255344   56   84820      208294          597              70          5.29   
255345   42   85109       60575          809              40         20.90   
255346   62   22418       18481          636             113          6.73   

       EmploymentType HasCoSigner  Default  
0           Full-time         Yes        0  
1           Full-time         Yes        0  
2          Unemployed          No        1  
3           Full-time          No        0  
4          Unemployed          No        0  
...               ...         ...      ...  
255342      Full-time          No        0  
255343      Part-time          No        1  
255344  Self-employed         Yes        0  
255345      Part-time          No        0  
255346     Unemployed         Yes        0  

[255347 rows x 9 columns]

In [44]:
x = new_data.iloc[:,np.r_[:8]].values
y = new_data.iloc[:,8].values
x

array([[56, 85994, 50587, ..., 15.23, 'Full-time', 'Yes'],
       [69, 50432, 124440, ..., 4.81, 'Full-time', 'Yes'],
       [46, 84208, 129188, ..., 21.17, 'Unemployed', 'No'],
       ...,
       [56, 84820, 208294, ..., 5.29, 'Self-employed', 'Yes'],
       [42, 85109, 60575, ..., 20.9, 'Part-time', 'No'],
       [62, 22418, 18481, ..., 6.73, 'Unemployed', 'Yes']], dtype=object)

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=.2,random_state = 2)

from sklearn.preprocessing import LabelEncoder
Labelencoder_x = LabelEncoder()

In [46]:
X_train[1:5]

array([[59, 147660, 111594, 712, 91, 6.18, 'Part-time', 'No'],
       [29, 25793, 52051, 385, 119, 20.77, 'Part-time', 'Yes'],
       [46, 69456, 44142, 349, 1, 16.93, 'Unemployed', 'Yes'],
       [66, 39950, 77815, 782, 95, 15.29, 'Part-time', 'No']],
      dtype=object)

In [47]:
for i in range(6,8):
    X_train[:,i]=Labelencoder_x.fit_transform(X_train[:,i])

X_train[1:5]

array([[59, 147660, 111594, 712, 91, 6.18, 1, 0],
       [29, 25793, 52051, 385, 119, 20.77, 1, 1],
       [46, 69456, 44142, 349, 1, 16.93, 3, 1],
       [66, 39950, 77815, 782, 95, 15.29, 1, 0]], dtype=object)

In [48]:
Labelencoder_y = LabelEncoder()
y_train=Labelencoder_y.fit_transform(y_train)
    
y_train

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [49]:
for i in range(6,8):
    X_test[:,i]=Labelencoder_x.fit_transform(X_test[:,i])
    
X_test[1:5]

array([[47, 121857, 8679, 701, 80, 18.15, 0, 0],
       [18, 109093, 142324, 351, 12, 3.59, 3, 1],
       [52, 49380, 133979, 530, 39, 21.0, 2, 1],
       [27, 44472, 85037, 766, 18, 14.54, 2, 0]], dtype=object)

In [50]:
y_test=Labelencoder_y.fit_transform(y_test)
    
y_test

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [51]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
X_train  = ss.fit_transform(X_train)
X_test = ss.fit_transform(X_test)

In [52]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier()
rf_clf.fit(X_train,y_train)

RandomForestClassifier()

In [53]:
from sklearn import metrics
y_pred = rf_clf.predict(X_test)

print("acc of Random Forest Classifier is",metrics.accuracy_score(y_pred,y_test))


acc of Random Forest Classifier is 0.8839631877814764


In [54]:
from sklearn.naive_bayes import GaussianNB

nb_clf = GaussianNB()
nb_clf.fit(X_train,y_train)

GaussianNB()

In [55]:
y_pred = nb_clf.predict(X_test)
print("acc of GaussianNB is",metrics.accuracy_score(y_pred,y_test))

acc of GaussianNB is 0.8835715684354807


In [56]:
from sklearn.tree import DecisionTreeClassifier
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [57]:
y_pred = dt_clf.predict(X_test)
print("acc of Decision Tree Classifier is",metrics.accuracy_score(y_pred,y_test))

acc of Decision Tree Classifier is 0.804366555707852


In [58]:
from sklearn.neighbors import KNeighborsClassifier
kn_clf = KNeighborsClassifier()
kn_clf.fit(X_train,y_train)

KNeighborsClassifier()

In [59]:
y_pred = kn_clf.predict(X_test)
print("acc of KNeighbors Classifier is",metrics.accuracy_score(y_pred,y_test))

acc of KNeighbors Classifier is 0.8718425690229097


In [60]:
import pickle
pickle.dump(nb_clf,open('rf21.pkl','wb'))

as random forest gives the highest accuracy among the other so we will go with the random forest 